[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[mgr.prepend_keymap]]
on   = "r"
run  = "rename --cursor=start"
desc = "Rename selected file(s)"

[[pick.append_keymap]]
on   = "O"
run  = "close"
desc = "Cancel pick"

[[mgr.prepend_keymap]]
on   = "z"
run  = "plugin zoxide"
desc = "Jump to a directory via zoxide"

[[mgr.prepend_keymap]]
on   = "Z"
run  = "plugin fzf"
desc = "Jump to a file/directory via fzf"

[[mgr.prepend_keymap]]
on = [ "g", "d" ]
run = "cd ~/Desktop"
desc = "Go to Desktop"

[[mgr.prepend_keymap]]
on = [ "g", "D" ]
run = "cd ~/Downloads"
desc = "Go to Downloads"

[[mgr.prepend_keymap]]
on = [ "g", "t" ]
run = "cd ~/.local/share/Trash/files"
desc = "Go to Trash"

[[mgr.prepend_keymap]]
on  = "<C-Enter>"
run = 'shell --block -- dragon-file "$1"'
