$ipc = qs -c noctalia-shell ipc call

# Shell keybinds
bind = Super, Backspace , exec, $ipc sessionMenu lock
bind = Super, Super_L   , exec, $ipc controlCenter toggle
bind = Super, comma     , exec, $ipc settings toggle
bind = Super, semicolon , exec, $ipc bluetooth togglePanel

# Window actions
bind = Super, Q, exec, $scriptPath/dontkillsteam.sh
bind = Super, W, togglefloating
bind = Super, F, fullscreen, 1

# Move focus
bind = Super, H, movefocus, l
bind = Super, L, movefocus, r
bind = Super, K, movefocus, u
bind = Super, J, movefocus, d

binde = Super Shift , L, resizeactive, 40  0
binde = Super Shift , H, resizeactive, -40 0
binde = Super Shift , K, resizeactive, 0   -40
binde = Super Shift , J, resizeactive, 0   40

bind = Super Control , H, movewindow, l
bind = Super Control , L, movewindow, r
bind = Super Control , K, movewindow, u
bind = Super Control , J, movewindow, d

bindm = Super, mouse:272 , movewindow
bindm = Super, mouse:273 , resizewindow

# Applications
bind = Super, Return , exec, $terminal
bind = Super, E      , exec, $fileExplorer
bind = Super, B      , exec, $browser

bind = Super, SPACE , exec, pkill -x rofi || rofi -show drun
bind = Super, V     , exec, $ipc launcher clipboard

bind = Super Shift, Return, exec, [float; size (monitor_w*0.6) (monitor_h*0.6)] $terminal

# Media
bindl = , XF86AudioPlay , exec, $ipc media playPause
bindl = , XF86AudioNext , exec, $ipc media next
bindl = , XF86AudioPrev , exec, $ipc media previous

# Volume
bindl = Shift, XF86AudioMute   , exec, $ipc volume muteInput
bindl = , XF86AudioMute        , exec, $ipc volume muteOutput
bindl = , XF86AudioRaiseVolume , exec, $ipc volume increase
bindl = , XF86AudioLowerVolume , exec, $ipc volume decrease

# Brightness
bindl = , XF86MonBrightnessUp   , exec, $ipc brightness increase
bindl = , XF86MonBrightnessDown , exec, $ipc brightness decrease

# Notifications
bind = Super, U, submap, notifications
submap = notifications

bind = , D       , exec, $ipc notifications toggleDND
bind = , A       , exec, $ipc notifications toggleHistory
bind = , N       , exec, $ipc toast dismiss

bind = Super, U, submap, reset
bind = , escape, submap, reset
submap = reset

# Power Profiles
bind = Super Alt, G, exec, $ipc powerProfile toggleNoctaliaPerformance

# Screenshots
bind = Super, P       , exec, hyprshot -m region --clipboard-only
bind = Super Shift, P , exec, hyprpicker -an

# Workspace actions
bind = Super, 1, workspace, 1
bind = Super, 2, workspace, 2
bind = Super, 3, workspace, 3
bind = Super, 4, workspace, 4
bind = Super, 5, workspace, 5
bind = Super, 6, workspace, 6
bind = Super, 7, workspace, 7
bind = Super, 8, workspace, 8
bind = Super, 9, workspace, 9
bind = Super, 0, workspace, empty

bind = Super, S, exec, $scriptPath/togglespecial

bind = Super Shift, 1, movetoworkspace, 1
bind = Super Shift, 2, movetoworkspace, 2
bind = Super Shift, 3, movetoworkspace, 3
bind = Super Shift, 4, movetoworkspace, 4
bind = Super Shift, 5, movetoworkspace, 5
bind = Super Shift, 6, movetoworkspace, 6
bind = Super Shift, 7, movetoworkspace, 7
bind = Super Shift, 8, movetoworkspace, 8
bind = Super Shift, 9, movetoworkspace, 9
bind = Super Shift, 0, movetoworkspace, 10

bind = Super Shift, S, movetoworkspace, special

bind = Super Alt, 1, movetoworkspacesilent, 1
bind = Super Alt, 2, movetoworkspacesilent, 2
bind = Super Alt, 3, movetoworkspacesilent, 3
bind = Super Alt, 4, movetoworkspacesilent, 4
bind = Super Alt, 5, movetoworkspacesilent, 5
bind = Super Alt, 6, movetoworkspacesilent, 6
bind = Super Alt, 7, movetoworkspacesilent, 7
bind = Super Alt, 8, movetoworkspacesilent, 8
bind = Super Alt, 9, movetoworkspacesilent, 9
bind = Super Alt, 0, movetoworkspacesilent, 10

bind = Super Alt, S, movetoworkspacesilent, special
