
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# idleinhibit rules
windowrule = idle_inhibit fullscreen, match:class ^(.*celluloid.*)$|^(.*mpv.*)$|^(.*vlc.*)$
windowrule = idle_inhibit fullscreen, match:class ^(.*[Ss]potify.*)$
windowrule = idle_inhibit fullscreen, match:class ^(.*LibreWolf.*)$|^(.*floorp.*)$|^(.*brave-browser.*)$|^(.*firefox.*)$|^(.*chromium.*)$|^(.*zen.*)$|^(.*vivaldi.*)$

windowrule = idle_inhibit always, match:class (steam_app_(default|[0-9]+))|gamescope

# Picture-in-Picture
windowrule {
    name = hyde_picture_in_picture
    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
    tag = +picture-in-picture
    tag = +hyde_picture_in_picture
    float = true
    keep_aspect_ratio = true
    move = (monitor_w*0.73) (monitor_h*0.72)
    size = (monitor_w*0.25) (monitor_h*0.25)
    pin = true
}

# Float

windowrule = float true, match:class blueman-manager
windowrule = float true, match:initial_class ^qt.*
# Games

windowrule = opaque true, match:class (steam_app_(default|[0-9]+))|gamescope
windowrule = immediate true, match:class (steam_app_(default|[0-9]+))|gamescope

# Workspace rules

workspace = w[tv1], gapsout:16

# Creative software

windowrule = opaque true, match:initial_class krita|gimp|inkscape|Unity|Godot|Alacritty|shotcut|blender|firefox|libresprite|HTTPie

# Special workspaces

windowrule = workspace special:music, match:initial_class Spotify|Spotatui

# Workspace rules

windowrule = xray on, match:workspace special:special
windowrule = xray on, match:workspace special:music

# Layer rules

layerrule = animation fade, match:namespace hyprpicker
layerrule = animation fade, match:namespace logout_dialog
layerrule = animation fade, match:namespace selection
layerrule = animation fade, match:namespace wayfreeze

layerrule {
  name = noctalia
  match:namespace = noctalia-background-.*$
  ignore_alpha = 1
  blur = true
}

windowrule {
    name = floating_apps
    match:initial_class = ^(Alacritty)
    match:initial_title = ^(Notepad|Explorer)$
    size = (monitor_w*0.6) (monitor_h*0.6)
    center = true
    float = true
}

windowrule {
    name = control_center_floater
    match:initial_class = ^(octopi.*|org.pulseaudio.pavucontrol)$
    size = (monitor_w*0.5) (monitor_h*0.5)
    center = true
    float = true
}

windowrule {
    name = ueberzug_floater
    match:initial_class = ^(ueberzugpp.*)$
    float = true
    no_focus = true
}
